version: '3'

services:
  deployment:
    build:
      context: .
      dockerfile: Dockerfile
    image: "document_sorting_assistant"
    ports:
      - "8000:8000"
    container_name: "document_sorting_assistant_cn"
    restart: unless-stopped
